/*
 Copyright Spotify AB 2012-2014. All rights reserved.
*/
var Spotify=Spotify||{};Spotify.Web=Spotify.Web||{};Spotify.Translations=Spotify.Translations||{};Spotify.Translations.missing=[];Spotify.Translations.mismatch=[];Spotify.Web.Screens=Spotify.Web.Screens||{};Spotify.Web.Forms=Spotify.Web.Forms||{};Spotify.Web.Settings=Spotify.Web.Settings||{};Spotify.Web.Storage=Spotify.Web.Storage||{};Spotify.Web.AP=Spotify.Web.AP||{};Spotify.Web.PostMessages=Spotify.Web.PostMessages||{};
var _=function(){var d=typeof window!=="undefined"?window:{},a=d.navigator,e=a&&a.userAgent&&a.userAgent.indexOf("Node")===-1&&!!d.console;return function(c,a){var b=((typeof window!=="undefined"?window:{}).spotLang||{})[c];b||(e&&console.error("No translation exists, falling back to input string:",c),Spotify.Translations.missing.push(c),b=c);return!a?b:b.replace(/\{\{\s?(.+?)\s?\}\}/g,function(c,d){var f=a[d]||"";f||(e&&console.error("Translation param length mismatch on string: ",b),Spotify.Translations.mismatch.push(b));
return f})}}();
(function(){if(typeof document!=="undefined")$("tr-loading").textContent=_("Loading"),$("about-link").textContent=_("About"),$("legal-link").textContent=_("Legal"),$("help-link").textContent=_("Help"),$$(".download-header").set("html",_("Thanks for downloading Spotify").replace("Spotify",'<span class="spotify">Spotify</span>')),$("tr-download-link-win").set("html",_("Your Spotify Download should start within seconds. If it doesn't, {{LINK_START}}restart the download{{LINK_END}}",{LINK_START:'<a href="http://download.spotify.com/Spotify%20Installer.exe">',LINK_END:"</a>"})),
$("tr-download-link-mac").set("html",_("Your Spotify Download should start within seconds. If it doesn't, {{LINK_START}}restart the download{{LINK_END}}",{LINK_START:'<a href="http://download.spotify.com/SpotifyInstaller.zip">',LINK_END:"</a>"})),$$(".tr-inst1").set("text",_("Download and Open")),$$(".tr-inst2").set("text",_("Run the installer")),$$(".need-more-help").set("html",_("Need more help? {{LINK_START}}Read the guide{{LINK_END}}",{LINK_START:'<a target="_blank" href="http://www.spotify.com/help/guides/account/">',
LINK_END:"</a>"})),$$(".tr-phone-header").set("text",_("Get a link to your phone")),$$(".tr-sms-sent").set("text",_("SMS Sent. Check your phone!")),$$(".tr-send-sms").set("text",_("Send SMS")),$$(".tr-sms-hint").set("text",_("The SMS is free (though carrier charges may apply)")),$$(".dividers-text").set("text",_("or")),$("tr-get-app-android").set("text",_("Get the app on Google Play")),$("tr-get-app-ios").set("text",_("Get the app on the App Store")),$$("input[name=phone_number]").set("placeholder",
_("Mobile phone number..."))})();
