"SpotifyRemote"in window||(window.SpotifyRemote={});SpotifyRemote.Type={DesktopClient:"desktop-client",WebPlayer:"webplayer"};
SpotifyRemote.Error={TRACK_UNAVAILABLE:"4303",USER_NOT_LOGGED_IN:"4110",message:{4001:"Unknown method",4002:"Error parsing request",4003:"Unknown service",4004:"Service not responding",4102:"Invalid OAuthToken",4103:"Expired OAuth token",4104:"OAuth token not verified",4105:"Token verification denied, too many requests",4106:"Token verification timeout",4107:"Invalid Csrf token",4108:"OAuth token is invalid for current user",4109:"Invalid Csrf path",4110:"No user logged in",4111:"Invalid scope",4112:"Csrf challenge failed",
4201:"Upgrade to premium",4202:"Upgrade to premium or wait",4203:"Billing failed",4204:"Technical error",4205:"Commercial is playing",4301:"Content is unavailable but can be purchased",4302:"Premium only content",4303:"Content unavailable","default":"Unexpected error. Please try again later."}};SpotifyRemote.createCookie=function(a,b,c){var d;if(c){d=new Date;d.setTime(d.getTime()+c*864E5);c="; expires="+d.toGMTString()}else c="";document.cookie=a+"="+b+c+"; path=/"};
SpotifyRemote.EventTarget=function(){this.events={playmodechanged:"PLAY_MODE_CHANGED",playpositionchanged:"PLAY_POSITION_CHANGED",volumechanged:"VOLUME_CHANGED",onclientopening:"ON_CLIENT_OPENING",onclientconnected:"ON_CLIENT_CONNECTED",onclientconnectionfailed:"ON_CLIENT_CONNECTION_FAILED",onclienterror:"ON_CLIENT_ERROR",onclientdisconnect:"ON_CLIENT_DISCONNECT"}};
SpotifyRemote.EventTarget.prototype.applyEventCallbacks=function(a){var b=this,c;for(c in this.events)if(this.events.hasOwnProperty(c)){var d=this.getCallbackName(c),e="add"+d,i="remove"+d.replace(/^on/i,"");(function(c){typeof a[e]==="undefined"&&(a[e]=function(a){b.subscribe(b.events[c],a)});typeof a[i]==="undefined"&&(a[i]=function(a){b.unsubscribe(b.events[c],a)})})(c)}return a};
SpotifyRemote.EventTarget.prototype.getCallbackName=function(a){var b=null;if(typeof this.events[a]!=="undefined"){a=this.events[a];a=a.toLowerCase();a=a.split("_");for(b=0;b<a.length;b++)a[b]=a[b].charAt(0).toUpperCase()+a[b].slice(1);b=a.join("")+"Listener"}return b};SpotifyRemote.EventTarget.prototype.subscribe=function(a,b){void 0===this.events[a]&&(this.events[a]=[]);this.events[a].push(b)};
SpotifyRemote.EventTarget.prototype.unsubscribe=function(a,b){for(var c=this.events[a],d=c.length-1;d>=0;--d)if(c[d]===b){c.splice(d,1);return true}return false};SpotifyRemote.EventTarget.prototype.dispatch=function(a,b,c){if(this.events[a])for(var c=c||this,b=b instanceof Array?b:[b],d,e=0,i=this.events[a].length;e<i;e++){d=this.events[a][e];d.apply(c,b)}};SpotifyRemote.settings={extend:function(a,b){var c,d;for(c in b){d=b[c];b.hasOwnProperty(c)&&typeof d!="undefined"&&(a[c]=d)}return a}};
SpotifyRemote.isDev=function(){return false};SpotifyRemote._isDev=null;"SpotifyRemote"in window||(window.SpotifyRemote={});"web"in SpotifyRemote||(SpotifyRemote.web={});SpotifyRemote.web.config={clientUrl:"https://play.spotify.com"};SpotifyRemote.web.getTrackUri=function(a){var b;if(/spotify:track:[a-z0-9]+/ig.test(a))return a;if((b=/^spotify:trackset:(\w+:)?([a-z0-9]+(,[a-z0-9]+)*)(#\d)?$/ig.exec(a))!==null){a=b[2].split(",");b=b[4]!==null?parseInt(b[4].substr(1)):0;b=b<a.length?a[b]:a[0];return"spotify:track:"+b}return a};
SpotifyRemote.web.remoteMessages=function(){return{messages:{STATUS_TO_REMOTE:"SPB_in",STATUS_FROM_REMOTE:"SPB_out",CONNECTED:"SPB_connected",CONNECT_REQUEST_FROM_REMOTE:"SPB_connect"},init:function(){return SpotifyRemote.web.localStorageMessages()}}}();SpotifyRemote.addEvent=function(a,b){window.addEventListener?window.addEventListener(a,b,false):window.attachEvent&&window.attachEvent("on"+a,b)};
SpotifyRemote.web.localStorageMessages=function(){function a(a){var f=a.key;if(c[f]&&document.location.href!==a.url)for(var a=b(a.newValue),g=0,h=c[f].length;g<h;g++){d=c[f][g];d.fn.apply(d.context||this,[a].concat(d.args))}}function b(a,b){var c="";try{var d=JSON.parse(a),c=b?JSON.stringify(d.data):d.data}catch(e){}return c}var c={},d,e=function(){var a=false;if(window.localStorage&&typeof window.localStorage.setItem==="function")try{var b="check-storage-"+Date.now();localStorage.setItem(b,Date.now());
localStorage.removeItem(b);a=true}catch(c){}return a}();e&&SpotifyRemote.addEvent("storage",a);return{send:function(a,b){var c=false,b=b||{};b.referrerUrl=location.href;b.reason="remote";if(e)try{var d={timestamp:Date.now(),data:b};localStorage.setItem(a,JSON.stringify(d));c=true}catch(j){}return c},listen:function(a,b,d,h){if(e){void 0===c[a]&&(c[a]=[]);c[a].push({fn:b,args:d,context:h})}},detach:function(a,b){if(e&&typeof c[a]!=="undefined"&&c[a].length>0)for(var d=0,h=c[a].length,j=null;d<h;d++){j=
c[a][d];if(j.fn==b){c[a].splice(d,1);h=h-1;d=d-1}}},read:function(a,c){var d=null;if(e){d=localStorage.getItem(a);d=b(d,c)}return d}}};var RemoteControlBridge=function(){function a(){f.send(g.CONNECTED,!1)}function b(a){e("status-message",a)}function c(){f.send(g.CONNECTED,!0);e("connection-request")}function d(a){var b={};try{b="object"==typeof a.data?a.data:JSON.parse(a.data)}catch(c){}if(!("undefined"===typeof b.key||a.origin!==i))switch(b.key){case "spb-error":case "spb-event":f.send(g.STATUS_TO_REMOTE,b.data)}}function e(a,b){window.parent.postMessage(JSON.stringify({key:a,data:b}),i)}var i=SpotifyRemote.web.config.clientUrl,
f=SpotifyRemote.web.remoteMessages.init(),g=SpotifyRemote.web.remoteMessages.messages;this.init=function(){try{window.addEventListener("message",d,!1),window.addEventListener("beforeunload",a,!1),f.send(g.CONNECTED,!0),f.listen(g.STATUS_FROM_REMOTE,b),f.listen(g.CONNECT_REQUEST_FROM_REMOTE,c),e("spb-connected")}catch(h){}}};var remoteControlBridge=new RemoteControlBridge;remoteControlBridge.init();
